---

- name: Install And Configure Docker Servers
  hosts: "{{ target_hosts | default('docker_servers') }}"
  become: yes
  gather_facts: yes
  roles:
    - { role: roles/docker_servers, become: True, tags: docker_setup }

...
